# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b368e1914093cd2600b5c806884cb93eae1dcd59f3c61976e5a695c2c295fa5876abec86ad76fb857906a1a902c6254869eca2ddb061e93d812ab4716ebad6af

test:
  secret_key_base: c810c26209c2ae1cde8ecba8b5402c21fec5e832d8e6c5ff6cfbff376ec92ac44938c163d9390abfea219336bb0a977d4a4691f54f1ff8a86e4be3af41e08d81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
